<html>
<head>
<title>@(package) Msg/Srv Documentation</title>
<link type="text/css" rel="stylesheet" href="../msg-styles.css" />
</head>
<body>

<div id="container">

<h1>@(package) Msg/Srv Documentation</h1>

@[for links, msg in zip(links, interface_list)]@
<li><a href="../../html/@(links)">@(msg)</a></li>
@[end for]@

<p class="footer"><small><em>autogenerated on @(date)</em></small></p>

</div>

</body>
</html>
